In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    "The cat chased the mouse.",
    "I enjoy reading good books.",
    "They walked through the park.",
    "The sky is bright blue.",
    "She baked a chocolate cake.",
    "We are going to school.",
    "He drives a fast car.",
    "My phone battery is low."
]


In [3]:
# Define the vocabulary size
voc_size = 10000

In [6]:
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[8250, 899, 9422, 8250, 4103],
 [144, 7445, 6067, 1265, 230],
 [7715, 2951, 9539, 8250, 4188],
 [8250, 1744, 9511, 6580, 6068],
 [8901, 4053, 76, 4727, 3617],
 [2551, 9805, 7578, 9402, 9602],
 [207, 242, 76, 7311, 1985],
 [5557, 5201, 3388, 9511, 133]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences 
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np 

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=8)
print(embedded_docs)

[[   0    0    0 8250  899 9422 8250 4103]
 [   0    0    0  144 7445 6067 1265  230]
 [   0    0    0 7715 2951 9539 8250 4188]
 [   0    0    0 8250 1744 9511 6580 6068]
 [   0    0    0 8901 4053   76 4727 3617]
 [   0    0    0 2551 9805 7578 9402 9602]
 [   0    0    0  207  242   76 7311 1985]
 [   0    0    0 5557 5201 3388 9511  133]]


Feature Representation

In [12]:
dim = 10

In [13]:
model = Sequential()

model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 18ms/step


array([[ 0.01567448,  0.04304339, -0.03148543,  0.04349372,  0.02190508,
         0.04050709, -0.0406986 , -0.01337341, -0.00919558, -0.04099067],
       [ 0.01567448,  0.04304339, -0.03148543,  0.04349372,  0.02190508,
         0.04050709, -0.0406986 , -0.01337341, -0.00919558, -0.04099067],
       [ 0.01567448,  0.04304339, -0.03148543,  0.04349372,  0.02190508,
         0.04050709, -0.0406986 , -0.01337341, -0.00919558, -0.04099067],
       [ 0.02540337,  0.01742646, -0.00790436, -0.03191113,  0.04965147,
         0.03981615,  0.02867975,  0.01156612,  0.02313707, -0.00564238],
       [-0.01583352, -0.02669426, -0.04196541,  0.01737544,  0.01536424,
        -0.03148125,  0.04589329, -0.02059658,  0.02554991, -0.03879876],
       [-0.03192351, -0.0455606 , -0.0119189 , -0.02030618,  0.01529605,
        -0.01960042, -0.0156378 ,  0.03506709,  0.01617089, -0.01465122],
       [ 0.02540337,  0.01742646, -0.00790436, -0.03191113,  0.04965147,
         0.03981615,  0.02867975,  0.01156612